# Generated by Django 3.1.3 on 2020-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('content_message', models.TextField()),
                ('file_path', models.TextField()),
                ('file_name', models.TextField()),
            ],
        ),
    ]
